import {
    faBars,faUser,faSignOutAlt,faClock,faDollarSign,faLocation,faGlobe,
    faCalendar,faListCheck,faUserClock,faUserGroup,
    faEnvelope,
    faPhone,
    faCopy,
    faCircleExclamation,
    faIdCard,
    faGear,
    faCircleUser,
    faClipboardList,
    faQuestion,
    faStickyNote,
    faTicket
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = {
    menu: faBars,
    user: faUser,
    logout: faSignOutAlt,
    dollar: faDollarSign,
    globe: faGlobe,
    location: faLocation,
    clock: faClock,
    calendar:faCalendar,
    faListCheck:faListCheck,
    faUserClock:faUserClock,
    faUserGroup:faUserGroup,
    envelope:faEnvelope,
    phone:faPhone,
    copy:faCopy,
    circle:faCircleExclamation,
    idCard:faIdCard,
    gear:faGear,
    circleUser:faCircleUser,
    clipboardList:faClipboardList,
    faQuestion:faQuestion,
    faSticky:faStickyNote,
    faTicket:faTicket,
    faUser:faUser,
}